# Generated by Django 4.2.3 on 2023-08-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_advertisement_delete_adertisement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisments',
        ),
    ]
